name: GitHub Actions Demo

on: 
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job Trigger event: ${{ github.event_name }}"
          echo "Name of branch: ${{ github.ref }} and your repository is ."
      
      - uses: actions/checkout@v3.3.0
      
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
                tree
